DROP TABLE AD_MEMBER;

CREATE TABLE AD_MEMBER(
	AID VARCHAR2(30) NOT NULL PRIMARY KEY,
	APASS VARCHAR2(30) NOT NULL,
	ANAME VARCHAR2(30) NOT NULL,
	ARESID NUMBER(20) NOT NULL,
	AGENDER VARCHAR2(10) NOT NULL,
	AJOB VARCHAR2(30) NOT NULL,
	APHONE NUMBER(20) NOT NULL,
	AEMAIL VARCHAR2(30) NOT NULL,
	APOST VARCHAR2(7) NOT NULL,
	AADDRESS VARCHAR2(200) NOT NULL,
	APERM VARCHAR2(30) NOT NULL,
	ADATE DATE
);